name: rector error
on: [push]
jobs:
  run-rector:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4','8.0' ]
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - run: php -v
      - run: php vendor/bin/rector
